[project]
authors = ["rcghpge <rcocker87@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Advent of Code 2024 Mojo"
name = "aoc-2024-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.8,<3.13"
max = ">=24.6.0,<25"
joblib = ">=1.4.2,<1.5"
regex = ">=2024.11.6,<2024.12"
colorama = ">=0.4.6,<0.5"
flask = ">=3.1.0,<3.2"
networkx = ">=3.4.2,<3.5"

